Drop Azure Arc ESU Dashboard
Azure/arc_jumpstart_drops pull request #119
Opened 2024-07-09 13:15 UTC by weeyin83

Add in a drop referencing an Azure Arc Windows ESU Dashboard that people can use to view their Arc and ESU status.

2024-07-09 16:24 UTC, fcabrera23 requested changes
Hi @weeyin83,

Thank you so much for your contribution. Great to see your work here as a Drop.   Just some minor issues to fix - Also, please review [write-up guidelines](https://arcjumpstart.com/contribution_guidelines). 

Thanks,
Francisco

2024-07-09 16:24 UTC, fcabrera23 commented on drops/arc_windows_esu_dashboard.json
> +    "Title": "Azure Arc Windows ESU Dashboard",
Try to avoid using acronyms in the title (ESU)

2024-07-09 16:24 UTC, fcabrera23 commented on .github/date-validator/validator.js
>  const getLatestCommit = (owner, repo, sourceUrl) => {
Please sync fork and rebase to remove this changes from the PR

2024-07-09 16:24 UTC, fcabrera23 commented on drops/arc_windows_esu_dashboard.json
> +    "Cover": "The dashboard provides a comprehensive view of Azure Arc-enabled Windows and Linux servers, showcasing the installed Arc agent count, operating system distribution, agent version detail
"Cover" -> should be "Description" . Also add "Cover" and you can leave that empty

2024-07-09 16:24 UTC, fcabrera23 commented on drops/arc_windows_esu_dashboard.json
> +    "Cover": "The dashboard provides a comprehensive view of Azure Arc-enabled Windows and Linux servers, showcasing the installed Arc agent count, operating system distribution, agent version detail
Also, Description generally it's a bit more detailed than summary

2024-07-09 16:24 UTC, fcabrera23 commented on drops/arc_windows_esu_dashboard.json
> +    "Difficulty": "Low",
Difficulty -> "Beginner"

2024-07-09 16:24 UTC, fcabrera23 commented on ui_dashboard_workbook/arc_windows_esu/_index.md
> +## Azure Arc Windows ESU Dashboard
Avoid ESU acronym as part of the title

2024-07-09 16:24 UTC, fcabrera23 commented on ui_dashboard_workbook/arc_windows_esu/_index.md
> +This dashboard has been created to enable you to view several elements of the Windows or Linux servers you have deployed the Azure Arc agent to in one simple view.   Within this dashboard you will be
extra space after "Within"

2024-07-09 16:24 UTC, fcabrera23 commented on ui_dashboard_workbook/arc_windows_esu/_index.md
> +    git clone https://github.com/Azure/arc_jumpstart_drops.git
Do you need to clone the repo? I'd suggest using the "Download" button to download only this Drop instead of getting the whole repo

2024-07-09 16:24 UTC, fcabrera23 commented on ui_dashboard_workbook/arc_windows_esu/_index.md
> +
What about Azure subscription? Arc enabled servers?  Az-cli? Any other extension required for arc?

2024-07-09 16:24 UTC, fcabrera23 commented on ui_dashboard_workbook/arc_windows_esu/_index.md
> +To import the workbook navigate to the [workbook directory](https://github.com/Azure/arc_jumpstart_drops/workbooks/arc_windows_esu)and run these Azure CLI commands:
Can you add a screen capture?

2024-07-09 16:24 UTC, fcabrera23 commented on ui_dashboard_workbook/arc_windows_esu/_index.md
> +
Suggestion to add screen captures of how the dashboard looks

2024-07-09 16:24 UTC, fcabrera23 commented on ui_dashboard_workbook/arc_windows_esu/_index.md
> +
What about for user running Windows? Bash is only for Linux, maybe also have the Windows version?

2024-07-09 16:24 UTC, fcabrera23 commented on ui_dashboard_workbook/arc_windows_esu/_index.md
> +To import the workbook navigate to the [workbook directory](https://github.com/Azure/arc_jumpstart_drops/workbooks/arc_windows_esu)and run these Azure CLI commands:
Also, missing space after [woorkbood directory]

2024-07-10 09:38 UTC, weeyin83 commented
Thanks for the feedback @fcabrera23, I've made the necessary changes.  Let me know your thoughts.  Thanks!

2024-07-10 16:00 UTC, fcabrera23 approved these changes
LGTM

2024-07-10 16:27 UTC, merged