Drop - Deploy a local Ubuntu server hosted with Vagrant and connect it to Azure Arc
Azure/arc_jumpstart_drops pull request #88
Opened 2024-06-24 21:27 UTC by mrhoads

this PR converts the Arc-enabled Server scenario for [deploying a local Ubuntu server hosted with Vagrant and connect it to Azure Arc](https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/vagrant/local_vagrant_ubuntu)

It's updated to work with multiple providers (e.g. Hyper-V, VirtualBox, libvirt, etc.)

2024-06-27 20:57 UTC, fcabrera23 requested changes
@mrhoads  could you please review?

2024-06-27 20:57 UTC, fcabrera23 commented on drops/arc_server_deploy_vagrant.json
> +    "LastModified": "",
Ensure to add LastModified and CreatedDate dates

2024-06-27 20:57 UTC, fcabrera23 commented on drops/arc_server_deploy_vagrant.json
> +    "Products": [
Maybe add ubuntu?

2024-06-27 20:57 UTC, fcabrera23 commented on drops/arc_server_deploy_vagrant.json
> +        "Name": "Mike Rhoads",
Who was the original owner? Maybe we could add him/her?

2024-06-27 20:57 UTC, fcabrera23 commented on drops/arc_server_deploy_vagrant.json
> +    "Products": [
Maybe also add Vagrant?

2024-07-08 15:27 UTC, mrhoads commented
I added:

- Ubuntu and Vagrant as products
- timestamp for LastModified and CreatedDate
- changed Author section to Lior Kamrat based on Git history

2024-07-08 19:57 UTC, fcabrera23 approved these changes
LGTM

2024-07-08 19:57 UTC, merged